spring:
  mvc:
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  http:
    encoding:
      force: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/clouddriver?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.hbm2ddl.auto: create
  transaction:
    rollback-on-commit-failure: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    pool:
      max-active: 32
      max-wait: -1
      max-idle: 8
      min-idle: 0
  cache:
    type: redis

server:
  address: 127.0.0.1
  port: 7777
  context-path: /
  tomcat:
    max-threads: 800
    uri-encoding: utf-8

# 使用log4j2替代默认的logback
# 1.spring-boot-starter中剔除spring-boot-starter-logging
# 2.配置log4j2.xml
logging:
  config: classpath:log4j2.xml


redis:
  expire:
    key: expire_manager_v1.0
    separator: '@'

